// Copyright The otelcconfig Authors
// SPDX-License-Identifier: Apache-2.0

package guard

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFixture(t *testing.T, name, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	return dir
}

func TestRunFlagsViolations(t *testing.T) {
	dir := writeFixture(t, "hook.go", `package hook

import (
	"os"

	"gopkg.in/yaml.v3"

	"github.com/ADITYA-CODE-SOURCE/otelcconfig/runtime"
)

func init() {
	runtime.Register(runtime.ConfigSnapshot{})
}

func Read() string {
	_ = runtime.NetHTTPClient()
	_ = os.Getenv("OTEL_GO_ENABLED_INSTRUMENTATIONS")
	_ = yaml.Unmarshal
	return ""
}
`)

	diags, err := Run([]string{dir})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	got := map[string]bool{}
	for _, d := range diags {
		got[d.Message] = true
	}
	for _, want := range []string{
		"runtime.Register is reserved for generated baked configuration; hooks must not replace the snapshot",
		"option value \"OTEL_GO_ENABLED_INSTRUMENTATIONS\" must come from the baked runtime configuration, not the environment",
		"hooks must not parse YAML at runtime; configuration is baked at build time",
	} {
		if !got[want] {
			t.Errorf("missing diagnostic: %v\ngot: %v", want, got)
		}
	}
}

func TestRunAllowsGeneratedRegister(t *testing.T) {
	dir := writeFixture(t, "baked.go", "// Code generated by otelcconfig. DO NOT EDIT.\n\npackage baked\n\n"+
		"import \"github.com/ADITYA-CODE-SOURCE/otelcconfig/runtime\"\n\nfunc init() {\n\truntime.Register(runtime.ConfigSnapshot{})\n}\n")
	diags, err := Run([]string{dir})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(diags) != 0 {
		t.Fatalf("generated file flagged: %v", diags)
	}
}

func TestRunSkipsTestAndGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	// A violating _test.go must be skipped.
	if err := os.WriteFile(filepath.Join(dir, "hook_test.go"),
		[]byte("package hook\nimport (\n\"os\"\n)\nfunc _() { _ = os.Getenv(\"OTEL_GO_ENABLED_INSTRUMENTATIONS\") }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// A violating _gen.go with a runtime.Register must also be skipped.
	if err := os.WriteFile(filepath.Join(dir, "snapshot_gen.go"),
		[]byte("package hook\nimport \"github.com/ADITYA-CODE-SOURCE/otelcconfig/runtime\"\nfunc init() { runtime.Register(runtime.ConfigSnapshot{}) }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	diags, err := Run([]string{dir})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
}

func TestRunAllowsNonOptionEnvReads(t *testing.T) {
	dir := writeFixture(t, "hook.go", "package hook\n\nimport \"os\"\n\nfunc Env() string { return os.Getenv(\"HOME\") }\n")
	diags, err := Run([]string{dir})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(diags) != 0 {
		t.Fatalf("non-option env read flagged: %v", diags)
	}
}

func TestRunAllowsYamlInTooling(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "cmd")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "config.go"),
		[]byte("package cfg\n\nimport \"gopkg.in/yaml.v3\"\n\nvar _ = yaml.Unmarshal\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	diags, err := Run([]string{dir})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(diags) != 0 {
		t.Fatalf("yaml import in tooling flagged: %v", diags)
	}
}

func TestRunRepoHooksAreClean(t *testing.T) {
	diags, err := Run([]string{"../../demo", "../../runtime", "../../baked"})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	var msgs []string
	for _, d := range diags {
		msgs = append(msgs, d.Pos.String()+": "+d.Message)
	}
	if len(msgs) != 0 {
		t.Fatalf("repo hook packages violate the contract:\n%s", strings.Join(msgs, "\n"))
	}
}

func TestRunMissingDir(t *testing.T) {
	if _, err := Run([]string{filepath.Join(t.TempDir(), "nope")}); err == nil {
		t.Fatal("Run on missing dir = nil error, want error")
	}
}
