// Copyright The otelcconfig Authors
// SPDX-License-Identifier: Apache-2.0

// Package guard is a static analyzer that rejects undeclared configuration
// access in instrumentation hook packages.
//
// Hooks must consume configuration exclusively through the typed runtime
// package, which is populated at build time by the generated baked package.
// guard enforces the runtime contract from
// docs/architecture.md#runtime-contract-implemented-in-phase-3:
//
//  1. runtime.Register is only called from generated baked code.
//  2. Option values are never read from the environment.
//  3. Hooks never parse YAML at runtime.
//
// The analyzer is import- and name-based (go/ast over a directory) rather than
// a full go/types pass, which keeps the module dependency-free. This is
// intentional for the prototype: it is a linter-grade check, not a proof of
// type soundness.
package guard

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RuntimePath is the module path of the runtime package.
const RuntimePath = "github.com/ADITYA-CODE-SOURCE/otelcconfig/runtime"

// BakedPath is the module path of the generated baked package.
const BakedPath = "github.com/ADITYA-CODE-SOURCE/otelcconfig/baked"

// ToolingSuffixes are path segments in which the YAML rule is suppressed.
var ToolingSuffixes = []string{"config", "cmd"}

// EnvOptionVars are environment variables that carry option values and so must
// only be read inside tooling.
var EnvOptionVars = []string{
	"OTEL_GO_ENABLED_INSTRUMENTATIONS",
	"OTEL_GO_DISABLED_INSTRUMENTATIONS",
}

// YamlImports are import paths that parse configuration YAML and are therefore
// forbidden in hook code.
var YamlImports = []string{
	"gopkg.in/yaml.v3",
}

const generatedMarker = "Code generated by otelcconfig. DO NOT EDIT."

// Diagnostic is a single guard finding.
type Diagnostic struct {
	Pos     token.Position
	Message string
}

// Run analyses every Go file in dirs (non-recursive) and returns the
// diagnostics found, sorted by position.
func Run(dirs []string) ([]Diagnostic, error) {
	if len(dirs) == 0 {
		dirs = []string{"."}
	}
	var all []Diagnostic
	seen := map[string]bool{}
	for _, dir := range dirs {
		files, err := goFiles(dir)
		if err != nil {
			return nil, err
		}
		for _, path := range files {
			if seen[path] {
				continue
			}
			seen[path] = true
			diags, err := analyzeFile(path)
			if err != nil {
				return nil, err
			}
			all = append(all, diags...)
		}
	}
	sort.Slice(all, func(i, j int) bool {
		if all[i].Pos.Filename != all[j].Pos.Filename {
			return all[i].Pos.Filename < all[j].Pos.Filename
		}
		if all[i].Pos.Line != all[j].Pos.Line {
			return all[i].Pos.Line < all[j].Pos.Line
		}
		return all[i].Pos.Column < all[j].Pos.Column
	})
	return all, nil
}

func goFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("guard: read directory %s: %w", dir, err)
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		if strings.HasSuffix(name, "_gen.go") {
			continue
		}
		files = append(files, filepath.Join(dir, name))
	}
	sort.Strings(files)
	return files, nil
}

func analyzeFile(path string) ([]Diagnostic, error) {
	fset := token.NewFileSet()
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("guard: read %s: %w", path, err)
	}
	generated := strings.Contains(string(data), generatedMarker)
	f, err := parser.ParseFile(fset, path, data, parser.AllErrors)
	if err != nil {
		return nil, fmt.Errorf("guard: parse %s: %w", path, err)
	}

	var diags []Diagnostic
	imports := map[string]string{} // local name -> import path
	for _, imp := range f.Imports {
		pathStr := strings.Trim(imp.Path.Value, `"`)
		var local string
		if imp.Name != nil {
			local = imp.Name.Name
		} else {
			local = pathStr[strings.LastIndex(pathStr, "/")+1:]
		}
		if pathStr == RuntimePath || pathStr == BakedPath {
			imports[local] = pathStr
		}
		if isYamlImport(pathStr) && !pathIsTooling(path) {
			diags = append(diags, Diagnostic{
				Pos:     fset.Position(imp.Pos()),
				Message: "hooks must not parse YAML at runtime; configuration is baked at build time",
			})
		}
	}

	envSet := map[string]bool{}
	for _, v := range EnvOptionVars {
		envSet[v] = true
	}

	ast.Inspect(f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		id, ok := sel.X.(*ast.Ident)
		if !ok {
			return true
		}
		recv := id.Name
		pkg, inImports := imports[recv]

		switch {
		case inImports && sel.Sel.Name == "Register" && pkg == RuntimePath && !generated:
			diags = append(diags, Diagnostic{
				Pos:     fset.Position(call.Pos()),
				Message: "runtime.Register is reserved for generated baked configuration; hooks must not replace the snapshot",
			})
		case recv == "os" && (sel.Sel.Name == "Getenv" || sel.Sel.Name == "LookupEnv"):
			if len(call.Args) == 0 {
				return true
			}
			lit, ok := call.Args[0].(*ast.BasicLit)
			if !ok {
				return true
			}
			varName := strings.Trim(lit.Value, `"`)
			if envSet[varName] {
				diags = append(diags, Diagnostic{
					Pos:     fset.Position(call.Pos()),
					Message: fmt.Sprintf("option value %q must come from the baked runtime configuration, not the environment", varName),
				})
			}
		}
		return true
	})
	return diags, nil
}

func isYamlImport(path string) bool {
	for _, y := range YamlImports {
		if path == y {
			return true
		}
	}
	return false
}

func pathIsTooling(path string) bool {
	for _, seg := range strings.Split(filepath.ToSlash(path), "/") {
		for _, suffix := range ToolingSuffixes {
			if seg == suffix {
				return true
			}
		}
	}
	return false
}
