// Copyright The otelcconfig Authors
// SPDX-License-Identifier: Apache-2.0

package codegen

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/ADITYA-CODE-SOURCE/otelcconfig/manifest"
)

const genHeader = "// Code generated by otelcconfig. DO NOT EDIT.\n\n"

func genTypes(m *manifest.Manifest) (string, []byte, error) {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("// Package types holds generated configuration types for otelc\n// instrumentations.\npackage types\n\n")

	fmt.Fprintf(&b, "// %s is the resolved behavior configuration for the %s\n// instrumentation.\n", m.StructName(), m.Instrumentation.Name)
	fmt.Fprintf(&b, "type %s struct {\n", m.StructName())
	for _, o := range m.Options {
		writeDocComment(&b, o.Description)
		fmt.Fprintf(&b, "\t%s %s\n", o.GoName(), goType(o.Type))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// Option paths for the %s instrumentation.\n", m.Instrumentation.Name)
	b.WriteString("const (\n")
	for _, o := range m.Options {
		fmt.Fprintf(&b, "\t%s = %q\n", "Option"+o.GoName(), o.DeclarativePath)
	}
	b.WriteString(")\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", nil, fmt.Errorf("format generated types for %s: %w", m.Instrumentation.Name, err)
	}
	return "types/" + m.InstrumentationFileName() + "_gen.go", src, nil
}

func writeDocComment(b *strings.Builder, text string) {
	for _, line := range strings.Split(strings.TrimSpace(text), "\n") {
		b.WriteString("// ")
		b.WriteString(line)
		b.WriteString("\n")
	}
}

func goType(t string) string {
	switch manifest.OptionType(t) {
	case manifest.TypeBoolean:
		return "bool"
	case manifest.TypeListString:
		return "[]string"
	default:
		return "any"
	}
}
