// Code generated by otelcconfig. DO NOT EDIT.

// Package baked holds configuration resolved and frozen into the
// binary at build time (`otelcconfig bake`). Instrumentation hooks
// consume it through the runtime package and never parse YAML.
package baked

import (
	"github.com/ADITYA-CODE-SOURCE/otelcconfig/generated/types"
	"github.com/ADITYA-CODE-SOURCE/otelcconfig/runtime"
)

func init() {
	runtime.Register(runtime.ConfigSnapshot{
		NetHTTPClient: types.NetHTTPClientConfig{
			Enabled: true,
			RequestCapturedHeaders: []string{
				"user-agent",
				"x-request-id",
			},
			SensitiveQueryParameters: []string{
				"token",
			},
		},
	})
}
