// Copyright The otelcconfig Authors
// SPDX-License-Identifier: Apache-2.0

package bake

import (
	"bytes"
	"encoding/json"
	"testing"

	"github.com/ADITYA-CODE-SOURCE/otelcconfig/config"
	"github.com/ADITYA-CODE-SOURCE/otelcconfig/generated/types"
)

func sampleResolved() []*config.Resolved {
	return []*config.Resolved{
		{
			Instrumentation: "nethttp.client",
			Options: []config.ResolvedOption{
				{Path: "go.nethttp.client.enabled", Value: false, Source: config.SourceFile},
				{Path: "general.http.client.request_captured_headers", Value: []string{"user-agent", "x-request-id"}, Source: config.SourceFile},
				{Path: "general.sanitization.url.sensitive_query_parameters", Value: []string{"token"}, Source: config.SourceFile},
			},
			NetHTTPClientConfig: &types.NetHTTPClientConfig{
				Enabled:                  false,
				RequestCapturedHeaders:   []string{"user-agent", "x-request-id"},
				SensitiveQueryParameters: []string{"token"},
			},
		},
	}
}

func TestGenerate(t *testing.T) {
	outs, err := Generate(sampleResolved())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(outs) != 2 {
		t.Fatalf("len(outs) = %d, want 2", len(outs))
	}
	src, ok := outs["nethttp_client_gen.go"]
	if !ok {
		t.Fatalf("missing nethttp_client_gen.go in %v", sortedPaths(outs))
	}
	for _, want := range []string{
		"// Code generated by otelcconfig. DO NOT EDIT.",
		"package baked",
		"runtime.Register(runtime.ConfigSnapshot{",
		"NetHTTPClient: types.NetHTTPClientConfig{",
		"Enabled: false",
		"RequestCapturedHeaders: []string{",
		`"user-agent",`,
		`"x-request-id",`,
		`"token",`,
	} {
		if !bytes.Contains(src, []byte(want)) {
			t.Errorf("generated source missing %q:\n%s", want, src)
		}
	}
	if _, ok := outs["nethttp_client.json"]; !ok {
		t.Fatalf("missing nethttp_client.json audit in %v", sortedPaths(outs))
	}
}

func TestGenerateDeterministic(t *testing.T) {
	a, err := Generate(sampleResolved())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	b, err := Generate(sampleResolved())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	for _, p := range sortedPaths(a) {
		if !bytes.Equal(a[p], b[p]) {
			t.Errorf("path %s not deterministic", p)
		}
	}
}

func TestGenerateEmpty(t *testing.T) {
	if _, err := Generate(nil); err == nil {
		t.Fatal("Generate(nil) = nil error, want error")
	}
}

func TestGenerateUnknownInstrumentation(t *testing.T) {
	_, err := Generate([]*config.Resolved{{Instrumentation: "grpc"}})
	if err == nil {
		t.Fatal("Generate with unknown instrumentation = nil error, want error")
	}
}

func TestJSONAuditMarshals(t *testing.T) {
	outs, err := Generate(sampleResolved())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	var doc map[string]any
	if err := json.Unmarshal(outs["nethttp_client.json"], &doc); err != nil {
		t.Fatalf("audit JSON invalid: %v", err)
	}
	if doc["instrumentation"] != "nethttp.client" {
		t.Fatalf("audit instrumentation = %v", doc["instrumentation"])
	}
}

func TestInstrumentationStem(t *testing.T) {
	if got := instrumentationStem("nethttp.client"); got != "nethttp_client" {
		t.Fatalf("instrumentationStem = %q, want nethttp_client", got)
	}
}
