// Copyright The otelcconfig Authors
// SPDX-License-Identifier: Apache-2.0

// Package bake freezes resolved configuration into a Go package that registers
// it with the runtime package at init, so instrumentation hooks never parse
// configuration at runtime.
//
// bake is deterministic: identical manifests, configuration file, and
// environment produce identical bytes for every generated path.
package bake

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"github.com/ADITYA-CODE-SOURCE/otelcconfig/codegen"
	"github.com/ADITYA-CODE-SOURCE/otelcconfig/config"
)

// packageName is the Go package emitted into the output directory.
const packageName = "baked"

// Generate produces the frozen configuration package for every resolved
// instrumentation. The returned map keys are relative to the output root:
// one <instrumentation>_gen.go file per instrumentation plus one
// <instrumentation>.json audit file.
func Generate(resolved []*config.Resolved) (codegen.Outputs, error) {
	if len(resolved) == 0 {
		return nil, fmt.Errorf("bake: no resolved configuration")
	}
	outs := codegen.Outputs{}
	for _, r := range resolved {
		src, err := generateGo(r)
		if err != nil {
			return nil, fmt.Errorf("bake %s: %w", r.Instrumentation, err)
		}
		formatted, err := format.Source(src)
		if err != nil {
			return nil, fmt.Errorf("bake %s: format generated source: %w", r.Instrumentation, err)
		}
		stem := instrumentationStem(r.Instrumentation)
		outs[stem+"_gen.go"] = formatted
		audit, err := json.MarshalIndent(r, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("bake %s: marshal audit: %w", r.Instrumentation, err)
		}
		outs[stem+".json"] = append(audit, '\n')
	}
	return outs, nil
}

// instrumentConfig resolves the typed configuration for one instrumentation.
type instrumentConfig struct {
	// Field is the ConfigSnapshot field that holds the configuration.
	Field string
	// Type is the generated configuration type.
	Type string
	// Value is the resolved configuration value.
	Value any
}

// configFor returns the typed configuration entry for a resolved
// instrumentation. It errors for instrumentations that have no generated
// configuration type yet.
func configFor(r *config.Resolved) (instrumentConfig, error) {
	switch r.Instrumentation {
	case "nethttp.client":
		if r.NetHTTPClientConfig == nil {
			return instrumentConfig{}, fmt.Errorf("nethttp.client resolved without typed config")
		}
		return instrumentConfig{Field: "NetHTTPClient", Type: "types.NetHTTPClientConfig", Value: r.NetHTTPClientConfig}, nil
	default:
		return instrumentConfig{}, fmt.Errorf("no generated configuration type for %q", r.Instrumentation)
	}
}

func generateGo(r *config.Resolved) ([]byte, error) {
	icfg, err := configFor(r)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by otelcconfig. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// Package %s holds configuration resolved and frozen into the\n", packageName)
	b.WriteString("// binary at build time (`otelcconfig bake`). Instrumentation hooks\n")
	b.WriteString("// consume it through the runtime package and never parse YAML.\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/ADITYA-CODE-SOURCE/otelcconfig/generated/types\"\n")
	b.WriteString("\t\"github.com/ADITYA-CODE-SOURCE/otelcconfig/runtime\"\n")
	b.WriteString(")\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\truntime.Register(runtime.ConfigSnapshot{\n")
	fmt.Fprintf(&b, "\t\t%s: %s{\n", icfg.Field, icfg.Type)
	if err := writeStructFields(&b, icfg.Value, 3); err != nil {
		return nil, err
	}
	b.WriteString("\t\t},\n")
	b.WriteString("\t})\n")
	b.WriteString("}\n")
	return b.Bytes(), nil
}

// writeStructFields writes Go composite-literal fields for a resolved
// configuration value, in struct definition order (deterministic).
// Supported field kinds: bool and []string (list_string).
func writeStructFields(b *bytes.Buffer, v any, depth int) error {
	rv := reflect.ValueOf(v)
	if rv.Kind() == reflect.Pointer {
		rv = rv.Elem()
	}
	if rv.Kind() != reflect.Struct {
		return fmt.Errorf("baked value is %s, want struct", rv.Kind())
	}
	t := rv.Type()
	for i := 0; i < rv.NumField(); i++ {
		if err := writeField(b, t.Field(i).Name, rv.Field(i), depth); err != nil {
			return err
		}
	}
	return nil
}

func writeField(b *bytes.Buffer, name string, rv reflect.Value, depth int) error {
	pad := strings.Repeat("\t", depth)
	switch rv.Kind() {
	case reflect.Bool:
		fmt.Fprintf(b, "%s%s: %s,\n", pad, name, strconv.FormatBool(rv.Bool()))
	case reflect.Slice:
		if rv.Type().Elem().Kind() != reflect.String {
			return fmt.Errorf("unsupported baked slice element type %s", rv.Type().Elem())
		}
		fmt.Fprintf(b, "%s%s: []string{\n", pad, name)
		for i := 0; i < rv.Len(); i++ {
			fmt.Fprintf(b, "%s%s,\n", pad, strconv.Quote(rv.Index(i).String()))
		}
		fmt.Fprintf(b, "%s},\n", pad)
	default:
		return fmt.Errorf("unsupported baked field type %s for %s", rv.Kind(), name)
	}
	return nil
}

// instrumentationStem converts an instrumentation name (nethttp.client) into a
// file stem (nethttp_client).
func instrumentationStem(name string) string {
	return strings.ReplaceAll(name, ".", "_")
}

// sortedPaths lists generated paths in stable order.
func sortedPaths(outs codegen.Outputs) []string {
	paths := make([]string, 0, len(outs))
	for p := range outs {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}
